server:
  port: 5002
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_AMQP_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
  application:
    name: Processing-Service
geoip:
  dbPath: "/GeoLite2-City.mmdb"