services:
  ingestion-service:
    build:
      context: .
      dockerfile: ./ingestion-service/Dockerfile
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_AMQP_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    env_file:
      - .env
    ports:
      - "${INGESTION_SERVICE_PORT}:5001"
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy

  processing-service:
    build:
      context: .
      dockerfile: ./processing-service/Dockerfile
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_AMQP_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    env_file:
      - .env
    ports:
      - "${PROCESSING_SERVICE_PORT}:5002"
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    env_file:
      - .env
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"
      - "${RABBITMQ_HTTP_PORT}:15672"
    networks:
      - backend
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    container_name: rabbitmq-service
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  elasticsearch:
    image: elasticsearch:9.0.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    env_file:
      - .env
    ports:
      - "${ELASTIC_SEARCH_PORT}:9200"
      - "9300:9300"
    networks:
      - backend
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    container_name: elasticsearch-service

networks:
  backend:
    driver: bridge

volumes:
  elastic_data:
  rabbitmq_data: