server:
  port: 5001
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_AMQP_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
  application:
    name: Ingestion-Service

app:
  authorization-server:
    base-url: http://${AUTHORIZATION_SERVER_HOST}:5004

logging:
  level:
    tdr.pet.ingestion: DEBUG