server:
  port: 5001
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_AMQP_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
  application:
    name: Ingestion-Service
logging:
  level:
    tdr.pet.ingestion: DEBUG