server:
  ssl:
    enabled: false
  address: ${AUTHORIZATION_SERVER_HOST}
  port: 5004
spring:
  sql:
    init:
      schema-locations: classpath:oauth2-schema.sql
      mode: always
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/users
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
