server:
  ssl:
    enabled: false
  address: ${AUTHORIZATION_SERVER_HOST}
  port: 5004

spring:
  sql:
    init:
      schema-locations: classpath:oauth2-schema.sql
      mode: always
      continue-on-error: false
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/sems_users
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

logging:
  level:
    tdr.pet.authorization: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE

auth:
  oauth2:
    clients:
#      - client-id: dashboard-client
#        client-secret: "${DASHBOARD_CLIENT_SECRET}"
#        grant-types:
#          - authorization_code
#          - refresh_token
#        redirect-uris:
#          - http://${DASHBOARD_HOST}:${DASHBOARD_PORT}/login/oauth2/code/dashboard-client
#        post-logout-uris:
#          - http://${DASHBOARD_HOST}:${DASHBOARD_PORT}/
#        scopes:
#          - openid
#          - profile
#        require-consent: true

      - client-id: ingestion-client
        client-secret: "${INGESTION_CLIENT_SECRET}"
        grant-types:
          - client_credentials
        scopes:
          - ingest:read
          - ingest:write
        require-consent: false