server:
  ssl:
    enabled: false
  address: ${AUTHORIZATION_SERVER_HOST:127.0.0.1}
  port: 5004
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/database
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
